env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - main: cmd/kail/main.go
    binary: kail
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
      - v2
      - v3
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w 
      - -X github.com/boz/tail/version.Version={{.Tag}} 
      - -X github.com/boz/tail/version.Commit={{.ShortCommit}} 
      - -X github.com/boz/tail/version.Date={{.Date}} 
      - -X github.com/boz/tail/version.BuiltBy=GoReleaser
      - -X github.com/boz/tail/version.OsName={{.Os}}
      - -X github.com/boz/tail/version.PlatformName={{.Arch}}

archives:
  - 
    name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'

brews:
  - tap:
      owner: boz
      name: homebrew-repo
      branch: master
    commit_author:
      name: boz
      email: adam.boz@gmail.com
    goamd64: v2
    homepage: "https://github.com/boz/kail"
    description: "kubernetes tail - pod log viewer"

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: boz
    name: kail
